---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pssp-prod-wrk-deployment
  labels:
    app: pssp-prod-wrk
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pssp-prod-wrk
  template:
    metadata:
      labels:
        app: pssp-prod-wrk
        env: prod
    spec:
      containers:
        - name: pssp-prod-wrk
          image: wallen/pssp-app-wrk:0.1.3
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: 10.98.221.249
