---
version: '3'
services:
    wallen-db:
        image: wallen/pssp-app-db:${VER}
        container_name: wallen-db
        ports:
            - 6441:6379
        user: "827385:815499"
        volumes:
            - ../data/:/data/
    wallen-api:
        image: wallen/pssp-app-api:${VER}
        container_name: wallen-api
        environment:
            - REDIS_IP=wallen-db
        ports:
            - 5041:5000
    wallen-wrk:
        image: wallen/pssp-app-wrk:${VER}
        container_name: wallen-wrk
        environment:
            - REDIS_IP=wallen-db
