---
version: '3'
services:
    nockolds-db:
        image: colenockolds/app-db:${VER}
        container_name: nockolds-db
        ports:
            - 6403:6379
        user: "827385:815499"
        volumes:
            - ../data/:/data/
    nockolds-api:
        image: colenockolds/app-api:${VER}
        container_name: nockolds-api
        environment:
            - REDIS_IP=nockolds-db
        ports:
            - 5023:5000
    nockolds-wrk:
        image: colenockolds/app-worker:${VER}
        container_name: nockolds-worker
        environment:
            - REDIS_IP=nockolds-db
